networks:
  db-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.18.1.0/24



services:

  db:
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    postgres_data:/var/lib/postgresql/data
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    networks:
      db-network:
        ipv4_address: 10.18.1.100
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: youtube-traker
    ports: 
      - 5432:5432

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    networks:
      db-network:
        ipv4_address: 10.18.1.101
    ports: 
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: emai@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
