# Generated by Django 6.0.1 on 2026-02-08 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('channel_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=50, unique=True)),
                ('etag', models.CharField(max_length=100)),
                ('channel_description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('country', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('playlist_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('playlist_title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('videos_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.channels')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('etag', models.CharField(max_length=100)),
                ('video_title', models.CharField(max_length=100)),
                ('duration', models.TimeField()),
                ('video_description', models.TextField(default='')),
                ('language', models.CharField(default='', max_length=5)),
                ('tags', models.TextField(default='')),
                ('dimension', models.CharField(default='', max_length=5)),
                ('definition', models.CharField(default='', max_length=5)),
                ('paid', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField()),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.channels')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistsVideos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('published_at', models.DateTimeField()),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.playlists')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.videos')),
            ],
        ),
    ]
