# Generated by Django 6.0.1 on 2026-02-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
